---
parent: Api_v1_orgs_branchid_users_userid
name: ApiV1OrgsBranchidUsersUseridPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/orgs/{branchId}/users/{userId}
endpoint: /api/v1/orgs/{{@Var.branchId}}/users/{{@Var.userId}}
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "createdBy" : "",
      "createdDate" : "",
      "id" : "",
      "inactive" : false,
      "modifiedBy" : "",
      "modifiedDate" : "",
      "org" : {
        "createdBy" : "",
        "createdDate" : "",
        "id" : "",
        "inactive" : false,
        "modifiedBy" : "",
        "modifiedDate" : "",
        "name" : "{{@Random}}",
        "version" : ""
      },
      "orgRole" : "USER",
      "status" : "INVITED",
      "users" : {
        "company" : "{{@Faker.company.name}}",
        "createdBy" : "",
        "createdDate" : "",
        "email" : "{{@Faker.internet.emailAddress}}",
        "id" : "",
        "inactive" : false,
        "jobTitle" : "{{@Faker.job.title}}",
        "location" : "{{@Random}}",
        "modifiedBy" : "",
        "modifiedDate" : "",
        "name" : "{{@Random}}",
        "username" : "{{@Faker.name.username}}",
        "version" : ""
      },
      "version" : ""
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
